---
- hosts: all
  tasks:
  - name: add hosts via eth1 without port forwarding
    changed_when: False
    add_host:
      name: "{{ item + '-eth1' }}"
      ansible_host: "{{ hostvars[item].ansible_eth1.ipv4.address }}"
      ansible_ssh_private_key_file: "{{ hostvars[item].ansible_ssh_private_key_file }}"
      ansible_user: "{{ hostvars[item].ansible_user }}"
      skip_reboot: "{{ hostvars[item].skip_reboot | d(True) }}"
      group: all_eth1
    with_items: "{{ ansible_play_hosts }}"

- hosts: all_eth1
  gather_facts: False
  roles:
  - { role: ansible-reboot-handler-role, reboot_confirm: False }

  pre_tasks:
  - name: save before uptime
    register: before
    command: uptime --since
    changed_when: False

  tasks:
  - name: force reboot notify 1
    register: trigger
    copy:
      dest: "/home/vagrant/A"
      force: no
      content: ""
    notify: "reboot system"

  - name: force reboot notify 2
    copy:
      dest: "/home/vagrant/B"
      force: no
      content: ""
    notify: "reboot system"

  post_tasks:
  - name: save after uptime
    register: after
    command: uptime --since
    changed_when: False

  - name: check boot time
    assert:
      that:
      - "(trigger | changed == True and skip_reboot == False) or before.stdout == after.stdout"
      - "(trigger | changed == False or skip_reboot == True) or before.stdout != after.stdout"
