---
- name: require the root permission
  register: can_become_as_root
  become: True
  become_user: root
  vars:
  - ansible_become: True
  - ansible_become_user: root
  command: id -u
  changed_when: False
  failed_when: >-
    can_become_as_root.rc is not defined
    or can_become_as_root.rc != 0
    or can_become_as_root.stdout_lines is not defined
    or can_become_as_root.stdout_lines | length != 1
    or can_become_as_root.stdout_lines[0] != "0"
